{% set name = "Pyttoresque" %}
{% set version = "0.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Pyttoresque-{{ version }}.tar.gz
  sha256: 3f07f39573480c5e3722b4b72728bd79a5f195372f05ba3930e4d8dab69c8f0d

build:
  entry_points:
    - jupyter-mosaic = pyttoresque.app:main
  number: 0

requirements:
  host:
    - pip
    - python
    - setuptools-scm
  run:
    - aiohttp
    - datashader
    - holoviews
    - jupyter-server-proxy
    - jupyterlab
    - numpy
    - panel
    - plotly
    - pycapnp
    - python

test:
  imports:
    - pyttoresque
  commands:
    - pip check
    - jupyter-mosaic --help
  requires:
    - pip

about:
  home: https://github.com/NyanCAD/pyttoresque
  summary: Library for working with NyanCAD tools
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pepijndevos
