{% set name = "Pyttoresque" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Pyttoresque-{{ version }}.tar.gz
  sha256: bc4aa1481ea188bc0115c44a9a50c1f252f6fefb0875a621c4dee4c4221a6964

build:
  entry_points:
    - jupyter-mosaic = pyttoresque.app:main
  number: 2

requirements:
  host:
    - pip
    - python
    - setuptools-scm
  run:
    - aiohttp
    - datashader
    - holoviews
    - jupyter-server-proxy
    - jupyterlab
    - numpy
    - panel
    - plotly
    - pycapnp
    - python

test:
  imports:
    - pyttoresque
  commands:
    - pip check
    - jupyter-mosaic --help
  requires:
    - pip

about:
  home: https://github.com/NyanCAD/pyttoresque
  summary: Library for working with NyanCAD tools
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pepijndevos
